# Generated by Django 5.0.3 on 2024-03-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyApp', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
